version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: micro-service-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
    - ./rabbitmqdata:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - micro-service

networks:
  micro-service:
    driver: bridge